variables:
    MARKDOWN: "markdown"
    LIBXML2: "libxml2-utils"

image: alpine:latest

stages:
    - build
    - test
    - deploy

build_website:
    stage: build
    script:
        - apk add $MARKDOWN
        - mkdir -p public/
        - markdown README.md > ./public/index.html
    artifacts:
        paths:
            - "public/index.html"

test_website:
    stage: test
    script:
        - apk add $LIBXML2
        - xmllint --html ./public/index.html
    dependencies:
        - build_website

deploy_qa:
    variables:
        S3_BUCKET: "my-markdown-website-qa"
    stage: deploy
    script:
        - apk add aws-cli
        - aws s3 cp ./public/ s3://$S3_BUCKET/ --recursive
    environment: qa
    dependencies:
        - build_website
    rules:
        - if: $CI_COMMIT_BRANCH == "main"

deploy_staging:
    variables:
        S3_BUCKET: "my-markdown-website-stage"
    stage: deploy
    script:
        - apk add aws-cli
        - aws s3 cp ./public/ s3://$S3_BUCKET/ --recursive
    environment: stage
    dependencies:
        - build_website
    rules:
        - if: $CI_COMMIT_TAG

deploy_prod:
    variables:
        S3_BUCKET: "my-markdown-website-prod"
    stage: deploy
    script:
        - apk add aws-cli
        - aws s3 cp ./public/ s3://$S3_BUCKET/ --recursive
    environment: prod
    dependencies:
        - build_website
    rules:
        - if: $CI_COMMIT_TAG
          when: manual
